const fs = require('fs');

const realProjects = [
  {
    id: "project-001",
    slug: "gig-video-showreel",
    title: "LENA — Generative Studio Showreel",
    subtitle: "Flagship AI Filmmaking & Visual Reel",
    category: "Cinematic",
    featured: true,
    thumbnail: "/videos/gig_video-Cover.jpg",
    previewVideo: "/videos/gig_video.mp4",
    fullVideo: "/videos/gig_video.mp4",
    aspectRatio: "16:9",
    duration: "1:00",
    client: "LENA Creative Studio",
    year: "2026",
    summary: "The official master showreel showcasing hyper-realistic AI commercials, cinematic camera choreography, fluid simulations, and visual effects.",
    description: "Synthesized through an advanced multimodal pipeline combining Google Veo, Kling AI, and Runway Gen-3. Mastered in 4K with custom cinematic sound design and foley synchronization.",
    tools: ["Google Veo", "Runway Gen-3", "Kling AI", "ElevenLabs", "CapCut Pro"],
    metrics: [
      { label: "Production Pacing", "value": "60 FPS" },
      { label: "Visual Fidelity", "value": "4K UHD" }
    ],
    tags: ["Showreel", "Cinematic", "Commercial", "Master Film"]
  },
  {
    id: "project-002",
    slug: "3d-quantum-lift",
    title: "QUANTUM LIFT — 3D Structural Motion",
    subtitle: "3D Product Dynamics & Particle Ad",
    category: "Product Videos",
    featured: true,
    thumbnail: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/3d_quantum_lift.mp4",
    fullVideo: "/videos/3d_quantum_lift.mp4",
    aspectRatio: "16:9",
    duration: "0:45",
    client: "Quantum Dynamics",
    year: "2026",
    summary: "Precision 3D particle simulation, exploded mechanical physics, and zero-G structural motion.",
    description: "Engineered with Kling AI and Runway Gen-3 for hyper-accurate volumetric lighting, refractive materials, and complex micro-mechanical interactions.",
    tools: ["Kling AI", "Runway Gen-3", "CapCut Pro"],
    metrics: [
      { label: "ROAS Lift", "value": "4.2x" },
      { label: "Engagement", "value": "9.4%" }
    ],
    tags: ["3D CGI", "Product Reveal", "Physics", "Sci-Fi"]
  },
  {
    id: "project-003",
    slug: "air-purifier-aero",
    title: "AERO PURE — Intelligent Air System",
    subtitle: "Micro-Fluid Particle & Airflow Visualization",
    category: "Product Videos",
    featured: true,
    thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/air_purifier.mp4",
    fullVideo: "/videos/air_purifier.mp4",
    aspectRatio: "16:9",
    duration: "0:35",
    client: "Aero Living Labs",
    year: "2026",
    summary: "Simulating invisible microscopic airflow channels, HEPA vortex filtration, and minimalist architectural design.",
    description: "Generated with Google Veo and Kling to showcase global interior illumination, transparent particle turbulence, and brushed aluminum textures.",
    tools: ["Google Veo", "Kling AI", "CapCut Pro"],
    metrics: [
      { label: "Conversions", "value": "+185%" },
      { label: "Ad Spend", "value": "$85k" }
    ],
    tags: ["Air Purifier", "Hardware", "Fluid Dynamics", "Commercial"]
  },
  {
    id: "project-004",
    slug: "glow-genie-serum",
    title: "GLOW GENIE — Cellular Radiance Ad",
    subtitle: "Luxury Skincare & Fluid Dynamics Commercial",
    category: "AI Ads",
    featured: true,
    thumbnail: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/Glow_Genie_7_Real.mp4",
    fullVideo: "/videos/Glow_Genie_7_Real.mp4",
    aspectRatio: "16:9",
    duration: "0:40",
    client: "Glow Genie Beauty",
    year: "2026",
    summary: "Ethereal golden hour liquid pours, botanical micro-droplets, and photorealistic cosmetic bottle illumination.",
    description: "Created using Runway Gen-3 and Kling image-to-video workflows to lock in packaging geometry while generating photorealistic fluid surface tension.",
    tools: ["Runway Gen-3", "Kling AI", "ElevenLabs", "CapCut Pro"],
    metrics: [
      { label: "Meta Ad ROAS", "value": "5.1x" },
      { label: "Units Sold", "value": "4,800+" }
    ],
    tags: ["Cosmetics", "Beauty", "Fluid Simulation", "Commercial"]
  },
  {
    id: "project-005",
    slug: "fitness-band-pro",
    title: "PULSE MATRIX — Smart Fitness Band",
    subtitle: "Wearable Tech & Biometric Haptic Visuals",
    category: "Product Videos",
    featured: true,
    thumbnail: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/fitness_band.mp4",
    fullVideo: "/videos/fitness_band.mp4",
    aspectRatio: "16:9",
    duration: "0:45",
    client: "Pulse Wearables",
    year: "2026",
    summary: "Visualizing biometric sensor pulses, sweat-resistant silicone textures, and dynamic OLED interface displays in motion.",
    description: "Crafted using Kling and Google Veo with precision lighting passes across curved glass and textured wrist straps.",
    tools: ["Google Veo", "Kling AI", "CapCut Pro"],
    metrics: [
      { label: "Pre-Orders", "value": "12,000+" },
      { label: "CTR Lift", "value": "+210%" }
    ],
    tags: ["Wearable", "Fitness", "Tech Gadget", "3D Reveal"]
  },
  {
    id: "project-006",
    slug: "focus-flow-brand",
    title: "FOCUS FLOW — Peak Cognitive State",
    subtitle: "High-Energy Lifestyle & Nootropic Commercial",
    category: "AI Ads",
    featured: true,
    thumbnail: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/FOCUSfLOW.mp4",
    fullVideo: "/videos/FOCUSfLOW.mp4",
    aspectRatio: "16:9",
    duration: "0:35",
    client: "FocusFlow Labs",
    year: "2026",
    summary: "Fast-paced kinetic transitions, neural synapse animations, and urban flow states engineered for high retention.",
    description: "Built using Kling AI with Higgsfield motion tracking. Audio engineered with ElevenLabs voiceover and synth soundtrack.",
    tools: ["Kling AI", "Higgsfield", "ElevenLabs", "CapCut Pro"],
    metrics: [
      { label: "TikTok Views", "value": "3.8M" },
      { label: "Conversion Rate", "value": "8.2%" }
    ],
    tags: ["High Energy", "Commercial", "Lifestyle", "Beverage"]
  },
  {
    id: "project-007",
    slug: "nanobrush-demo",
    title: "NANO-BRUSH — Micro-Sonic Dental Tech",
    subtitle: "Ultrasonic Wave & Bristle Simulation",
    category: "Product Videos",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/DEMO_FOR_NANObrush.mp4",
    fullVideo: "/videos/DEMO_FOR_NANObrush.mp4",
    aspectRatio: "16:9",
    duration: "0:45",
    client: "NanoSonic Oral",
    year: "2026",
    summary: "Extreme macro simulation of 40,000 VPM sonic vibrations, water droplet cavitation, and micro-bristle motion.",
    description: "Rendered with Runway Gen-3 and Kling AI using micro depth-of-field control.",
    tools: ["Runway Gen-3", "Kling AI", "CapCut Pro"],
    tags: ["Oral Care", "Macro", "Product Demo", "Sonic Tech"]
  },
  {
    id: "project-008",
    slug: "raffaella-couture",
    title: "RAFFAELLA — Haute Couture AI Film",
    subtitle: "High Fashion & Digital Garment Runway",
    category: "Cinematic",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/RAFFaELLA_update.mp4",
    fullVideo: "/videos/RAFFaELLA_update.mp4",
    aspectRatio: "16:9",
    duration: "1:10",
    client: "Maison Raffaella",
    year: "2026",
    summary: "Haute couture models donning iridescent, silk-fluid garments walking a minimalist obsidian runway.",
    description: "Created with Higgsfield and Kling AI for authentic fabric drape, catwalk strides, and high-fashion editorial lighting.",
    tools: ["Higgsfield", "Kling AI", "Fish Audio", "CapCut Pro"],
    tags: ["Fashion", "Runway", "Haute Couture", "Cinematic"]
  },
  {
    id: "project-009",
    slug: "fit4-extreme-performance",
    title: "FIT4 — Unleash The Velocity",
    subtitle: "Athletic Performance Commercial",
    category: "AI Ads",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/FIT4.mp4",
    fullVideo: "/videos/FIT4.mp4",
    aspectRatio: "16:9",
    duration: "0:30",
    client: "Fit4 Apparel",
    year: "2026",
    summary: "Kinetic sprint tracking, muscle fiber tension visualization, and high-intensity workout choreography.",
    description: "Produced with Kling AI and ElevenLabs for heavy bass impact and dynamic athletic transitions.",
    tools: ["Kling AI", "ElevenLabs", "CapCut Pro"],
    tags: ["Fitness", "Athletics", "Commercial", "Adrenaline"]
  },
  {
    id: "project-010",
    slug: "packing-cubes-system",
    title: "MODULAR VOYAGE — Compression Gear",
    subtitle: "Smart Travel Gear & UGC Ad Campaign",
    category: "UGC",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/packing_cubes_2nd_draft.mp4",
    fullVideo: "/videos/packing_cubes_2nd_draft.mp4",
    aspectRatio: "16:9",
    duration: "0:50",
    client: "Voyage Gear Co",
    year: "2026",
    summary: "High-converting UGC demonstration of space-saving luggage organization and zipper compression physics.",
    description: "Engineered with Seedance persona avatars and Kling AI for authentic unboxing and packing demonstrations.",
    tools: ["Seedance", "Kling AI", "CapCut Pro"],
    tags: ["UGC", "Travel", "Product Demo", "E-Commerce"]
  },
  {
    id: "project-011",
    slug: "dunamis-cinematic",
    title: "DUNAMIS — The Power Within",
    subtitle: "Epic Brand Anthem & Visual Journey",
    category: "Cinematic",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/DUNNAMIS_F.mp4",
    fullVideo: "/videos/DUNNAMIS_F.mp4",
    aspectRatio: "16:9",
    duration: "1:20",
    client: "Dunamis Global",
    year: "2026",
    summary: "A sweeping cinematic odyssey traversing volcanic peaks, deep space nebula vistas, and cybernetic cities.",
    description: "Developed with Google Veo and Runway Gen-3 with custom orchestral score integration.",
    tools: ["Google Veo", "Runway Gen-3", "Fish Audio", "CapCut Pro"],
    tags: ["Cinematic", "Brand Anthem", "Epic", "Sci-Fi"]
  },
  {
    id: "project-012",
    slug: "adp-finale-reveal",
    title: "ADP HORIZON — Enterprise Brand Campaign",
    subtitle: "Next-Gen Corporate & Innovation Visuals",
    category: "AI Ads",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/ADP_FINALE.mp4",
    fullVideo: "/videos/ADP_FINALE.mp4",
    aspectRatio: "16:9",
    duration: "1:05",
    client: "ADP International",
    year: "2026",
    summary: "Sleek architectural glass corporate metropolises, quantum data streams, and executive vision storytelling.",
    description: "Crafted using Google Veo and Kling AI for photorealistic reflections, glass refractions, and corporate elegance.",
    tools: ["Google Veo", "Kling AI", "ElevenLabs", "CapCut Pro"],
    tags: ["Corporate", "Enterprise", "Commercial", "Innovation"]
  },
  {
    id: "project-013",
    slug: "dental-ultrasonic-care",
    title: "LUMINOUS DENTAL — Advanced Oral Hygiene",
    subtitle: "Medical & Ultrasonic Product Ad",
    category: "Product Videos",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/dental_latest.mp4",
    fullVideo: "/videos/dental_latest.mp4",
    aspectRatio: "16:9",
    duration: "0:30",
    client: "Luminous Health",
    year: "2026",
    summary: "Clear medical-grade fluid dynamics, sparkling enamel light refractions, and high-tech sonic wand motion.",
    description: "Engineered with Runway Gen-3 and Kling AI for crisp cleanroom lighting and fluid dynamics.",
    tools: ["Runway Gen-3", "Kling AI", "CapCut Pro"],
    tags: ["Health", "Medical", "Dental", "Product Video"]
  },
  {
    id: "project-014",
    slug: "demo-video-chris-ugc",
    title: "CREATOR HOOKS — Viral Persona Ad Suite",
    subtitle: "AI Digital Creator Testimonials",
    category: "UGC",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/demo_video_chris.mp4",
    fullVideo: "/videos/demo_video_chris.mp4",
    aspectRatio: "16:9",
    duration: "0:45",
    client: "Direct Creator Network",
    year: "2026",
    summary: "Hyper-realistic AI creator personas speaking with organic rhythm and micro-facial authenticity.",
    description: "Synthesized via Seedance and ElevenLabs voice cloning.",
    tools: ["Seedance", "ElevenLabs", "CapCut Pro"],
    tags: ["UGC", "Creator", "Conversion", "Testimonial"]
  },
  {
    id: "project-015",
    slug: "quantum-social-reel-01",
    title: "NEO-VELOCITY — Vertical Short-Form Reel",
    subtitle: "High-Engagement Instagram & TikTok Cut",
    category: "Social",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/0315_1_.mp4",
    fullVideo: "/videos/0315_1_.mp4",
    aspectRatio: "16:9",
    duration: "0:25",
    client: "Velocity Media",
    year: "2026",
    summary: "Rapid-fire visual hooks engineered specifically for high swipe-through and retention metrics.",
    description: "Rendered with Kling AI and optimized for mobile social feeds.",
    tools: ["Kling AI", "CapCut Pro"],
    tags: ["Social", "Viral", "Reels", "High Retention"]
  },
  {
    id: "project-016",
    slug: "speculative-motion-02",
    title: "SYNTHETICA — Generative Art Piece",
    subtitle: "Experimental Latent Space Animation",
    category: "Animation",
    featured: false,
    thumbnail: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
    previewVideo: "/videos/0406__2_.mp4",
    fullVideo: "/videos/0406__2_.mp4",
    aspectRatio: "16:9",
    duration: "0:45",
    client: "Digital Horizon Gallery",
    year: "2026",
    summary: "Surreal geometric morphogenesis and continuous fluid-matter transitions.",
    description: "Interpolated with Runway Gen-3 and Kling AI.",
    tools: ["Runway Gen-3", "Kling AI", "CapCut Pro"],
    tags: ["Animation", "Generative Art", "Latent Space", "Surreal"]
  }
];

fs.writeFileSync('src/data/projects.json', JSON.stringify(realProjects, null, 2));
console.log(`Updated src/data/projects.json with ${realProjects.length} real Google Drive video projects!`);

